name: Go Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build binary
        run: |
          mkdir -p build
          binary_name=track-${{ steps.get_version.outputs.version }}-${{ matrix.goos }}-${{ matrix.goarch }}
          output_path=build/$binary_name

          # Compile Go binary
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 go build -o $output_path ./...

          # Zip the binary
          cd build
          zip $binary_name.zip $binary_name
          cd ..
        shell: bash

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
